import type { Metadata } from "next";
import "./globals.css";
import { notoSans } from "./fonts/fonts";
import Providers from "@/components/Providers/Providers";
import MythModal from "@/components/Modals/MythModal/MythModal";
import RealModal from "@/components/Modals/RealModal/RealModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full">
      <Providers>
        <body className={`relative h-full antialiased ${notoSans.className}`}>
          <div id="modal" />
          <main className="relative flex flex-col items-center min-h-screen">
            <div className="flex-grow flex-1 2xl:w-full w-[95%] max-w-[1380px] wrapper">
              {children}
            </div>
          </main>
          <MythModal />
          <RealModal />
        </body>
      </Providers>
    </html>
  );
}
